global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']  # Target the metrics endpoint of the Collector
